### ISSUE TITLE
the result of change_ecc_inc is far from the desired values

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1383]
🐞 **Problem**

```python
import numpy as np
from numpy.testing import assert_allclose
from astropy import units as u
from poliastro.twobody.thrust import change_ecc_inc
from poliastro.twobody import Orbit
from poliastro.bodies import Sun
from poliastro.core.propagation import func_twobody
from poliastro.twobody.propagation import propagate, cowell

orbit = Orbit.from_vectors(Sun, r=np.array([-3.87956134e+08,  1.05155086e+08,  1.30885524e+07]) << u.km,
                           v=np.array([ -4.96831485, -18.42591704,  -0.09133032]) << (u.km / u.s))

a_d, deltav, t_f = change_ecc_inc(orbit, ecc_f = 0, inc_f = 0, f = 1e-4 << (u.m / u.s ** 2))

def apply_thrust(orbit, t_f, a_d):
    def f(t0, state, k):
        du_kep = func_twobody(t0, state, k)
        ax, ay, az = a_d(
            t0,
            state,
            k,
        )
        du_ad = np.array([0., 0., 0., ax, ay, az])
        # print(t0, end=':')
        # print(du_kep, end=':')
        # print(du_ad)
        return du_kep + du_ad
    return orbit.propagate(t_f, method=cowell, rtol=1e-9, f=f)

orbit = apply_thrust(orbit, t_f, a_d)
assert_allclose(orbit.inc, 0.)
assert_allclose(orbit.ecc, 0.)
```

```
In [2]: orbit.inc
Out[2]: <Quantity 0.17070543 rad>

In [3]: orbit.ecc
Out[3]: <Quantity 0.0282447>
```

They look very far from what was expected.

**Comment by MLopez-Ibanez** [comment]
Maybe related to #1382

**Comment by astrojuanlu** [comment]
Yep, I think this is essentially a duplicate of #1382. Let's continue the discussion there.

**Comment by MLopez-Ibanez** [comment]
Please reopen, this is not a duplicate of #1382

**Comment by MLopez-Ibanez** [comment]
This may be a good reference to check: https://link.springer.com/article/10.1007/s10569-021-10033-9#Equ32

Unfortunately this is beyond my knowledge of astrophysics. I cannot get Eq 38 to work with poliastro's propagation.

**Comment by jfrchicanog** [comment]
I think the problem could be that the force is not changes to km/s^2 in method: https://github.com/poliastro/poliastro/blob/75d13ce4fc28355ea00fc4b79e1b6a90a34bf60b/src/poliastro/twobody/thrust/change_ecc_inc.py#L18

**Comment by jfrchicanog** [comment]
This seems to solve the error in the eccentricity. However, I still notice a problem with the inclination. When it is increased it works well, but when it should be decreased it is increased. I think this could be related with the sign of beta.

**Comment by MLopez-Ibanez** [comment]
> I think the problem could be that the force is not changes to km/s^2 in method:

Yes, that is another problem fixed by #1389

**Comment by astrojuanlu** [comment]
Unclear if the problem was fully fixed in #1389?

**Comment by MLopez-Ibanez** [comment]
> Unclear if the problem was fully fixed in #1389?

Not fixed:

> This seems to solve the error in the eccentricity. However, I still notice a problem with the inclination. When it is increased it works well, but when it should be decreased it is increased. I think this could be related with the sign of beta.

This is a comment about the original code that still applies. But I wonder also whether the formulas have some restrictions/assumptions that the code is not checking for that explain the large errors. In any case, the example above still doesn't work well.

**Comment by astrojuanlu** [comment]
The original code cannot be used anymore as a reproducer, we changed the API a bit, but it would be nice to get confirmation from it. Otherwise we can just close.
